import type { SheetColumn } from "@/repositories/google-sheets/sheet-mapper";
import type {
  AuditLog,
  Client,
  ContentItem,
  Deal,
  Employee,
  FinanceRecord,
  Invitation,
  Lead,
  Meeting,
  Notification,
  Payment,
  PipelineMovement,
  Project,
  Task,
} from "@/types/domain";

export const sheetNames = {
  employees: "Employees",
  invitations: "Invitations",
  leads: "Leads",
  deals: "Deals",
  pipelineMovements: "PipelineMovements",
  clients: "Clients",
  clientContacts: "ClientContacts",
  projects: "Projects",
  tasks: "Tasks",
  content: "Content",
  meetings: "Meetings",
  finance: "Finance",
  payments: "Payments",
  auditLogs: "AuditLogs",
  notifications: "Notifications",
  activity: "Activity",
  settings: "Settings",
  rolePermissions: "RolePermissions",
} as const;

export const employeeColumns: Array<SheetColumn<Employee & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "name", header: "name", required: true },
  { key: "email", header: "email", required: true },
  { key: "phone", header: "phone" },
  { key: "role", header: "role", required: true },
  { key: "department", header: "department" },
  { key: "managerId", header: "managerId" },
  { key: "joiningDate", header: "joiningDate" },
  { key: "status", header: "status", required: true },
  { key: "accessLevel", header: "accessLevel" },
  { key: "leaveStatus", header: "leaveStatus" },
  { key: "workloadCapacity", header: "workloadCapacity" },
  { key: "avatarUrl", header: "avatarUrl" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const invitationColumns: Array<SheetColumn<Invitation & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "email", header: "email", required: true },
  { key: "name", header: "name", required: true },
  { key: "role", header: "role", required: true },
  { key: "department", header: "department" },
  { key: "managerId", header: "managerId" },
  { key: "accessLevel", header: "accessLevel" },
  { key: "status", header: "status", required: true },
  { key: "invitedBy", header: "invitedBy", required: true },
  { key: "invitedAt", header: "invitedAt", required: true },
  { key: "expiresAt", header: "expiresAt" },
  { key: "acceptedAt", header: "acceptedAt" },
  { key: "revokedAt", header: "revokedAt" },
];

export const auditLogColumns: Array<SheetColumn<AuditLog & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "userId", header: "userId", required: true },
  { key: "action", header: "action", required: true },
  { key: "entityType", header: "entityType", required: true },
  { key: "entityId", header: "entityId", required: true },
  { key: "oldValue", header: "oldValue" },
  { key: "newValue", header: "newValue" },
  { key: "metadata", header: "metadata" },
  { key: "createdAt", header: "createdAt", required: true },
];

export const leadColumns: Array<SheetColumn<Lead & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "company", header: "company", required: true },
  { key: "contactName", header: "contactName", required: true },
  { key: "email", header: "email" },
  { key: "phone", header: "phone" },
  { key: "website", header: "website" },
  { key: "industry", header: "industry" },
  { key: "source", header: "source" },
  { key: "serviceInterested", header: "serviceInterested" },
  { key: "dealValue", header: "dealValue" },
  { key: "ownerId", header: "ownerId", required: true },
  { key: "stage", header: "stage", required: true },
  { key: "probability", header: "probability" },
  { key: "expectedCloseDate", header: "expectedCloseDate" },
  { key: "lastContact", header: "lastContact" },
  { key: "nextAction", header: "nextAction" },
  { key: "notes", header: "notes" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const dealColumns: Array<SheetColumn<Deal & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "leadId", header: "leadId", required: true },
  { key: "company", header: "company", required: true },
  { key: "contactName", header: "contactName" },
  { key: "ownerId", header: "ownerId", required: true },
  { key: "value", header: "value", required: true },
  { key: "stage", header: "stage", required: true },
  { key: "probability", header: "probability", required: true },
  { key: "expectedCloseDate", header: "expectedCloseDate" },
  { key: "lastContact", header: "lastContact" },
  { key: "nextAction", header: "nextAction" },
  { key: "wonAt", header: "wonAt" },
  { key: "lostAt", header: "lostAt" },
  { key: "lostReason", header: "lostReason" },
  { key: "convertedClientId", header: "convertedClientId" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const pipelineMovementColumns: Array<
  SheetColumn<PipelineMovement & Record<string, unknown>>
> = [
  { key: "id", header: "id", required: true },
  { key: "dealId", header: "dealId", required: true },
  { key: "leadId", header: "leadId", required: true },
  { key: "previousStage", header: "previousStage", required: true },
  { key: "newStage", header: "newStage", required: true },
  { key: "actorId", header: "actorId", required: true },
  { key: "reason", header: "reason", required: true },
  { key: "notes", header: "notes" },
  { key: "dealValue", header: "dealValue", required: true },
  { key: "nextAction", header: "nextAction" },
  { key: "createdAt", header: "createdAt", required: true },
];

export const clientColumns: Array<SheetColumn<Client & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "companyName", header: "companyName", required: true },
  { key: "primaryContactName", header: "primaryContactName" },
  { key: "primaryEmail", header: "primaryEmail" },
  { key: "primaryPhone", header: "primaryPhone" },
  { key: "website", header: "website" },
  { key: "industry", header: "industry" },
  { key: "service", header: "service" },
  { key: "accountManagerId", header: "accountManagerId" },
  { key: "sourceLeadId", header: "sourceLeadId" },
  { key: "sourceDealId", header: "sourceDealId" },
  { key: "driveFolderId", header: "driveFolderId" },
  { key: "driveFolderUrl", header: "driveFolderUrl" },
  { key: "onboardingStatus", header: "onboardingStatus" },
  { key: "health", header: "health", required: true },
  { key: "recurringValue", header: "recurringValue" },
  { key: "renewalDate", header: "renewalDate" },
  { key: "status", header: "status", required: true },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const projectColumns: Array<SheetColumn<Project & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "clientId", header: "clientId", required: true },
  { key: "projectName", header: "projectName", required: true },
  { key: "type", header: "type" },
  { key: "ownerId", header: "ownerId", required: true },
  { key: "teamMemberIds", header: "teamMemberIds" },
  { key: "startDate", header: "startDate" },
  { key: "dueDate", header: "dueDate" },
  { key: "status", header: "status", required: true },
  { key: "priority", header: "priority", required: true },
  { key: "budget", header: "budget" },
  { key: "health", header: "health", required: true },
  { key: "description", header: "description" },
  { key: "driveLink", header: "driveLink" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const taskColumns: Array<SheetColumn<Task & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "title", header: "title", required: true },
  { key: "description", header: "description" },
  { key: "clientId", header: "clientId" },
  { key: "projectId", header: "projectId" },
  { key: "assignedToId", header: "assignedToId", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "priority", header: "priority", required: true },
  { key: "status", header: "status", required: true },
  { key: "startDate", header: "startDate" },
  { key: "dueDate", header: "dueDate" },
  { key: "estimatedTime", header: "estimatedTime" },
  { key: "actualTime", header: "actualTime" },
  { key: "driveLink", header: "driveLink" },
  { key: "comments", header: "comments" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const notificationColumns: Array<
  SheetColumn<Notification & Record<string, unknown>>
> = [
  { key: "id", header: "id", required: true },
  { key: "recipientUserId", header: "recipientUserId", required: true },
  { key: "type", header: "type", required: true },
  { key: "title", header: "title", required: true },
  { key: "message", header: "message", required: true },
  { key: "entityType", header: "entityType" },
  { key: "entityId", header: "entityId" },
  { key: "link", header: "link" },
  { key: "readAt", header: "readAt" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "deliveryStatus", header: "deliveryStatus", required: true },
];

export const contentColumns: Array<SheetColumn<ContentItem & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "clientId", header: "clientId", required: true },
  { key: "accountId", header: "accountId" },
  { key: "platform", header: "platform" },
  { key: "contentType", header: "contentType" },
  { key: "topic", header: "topic" },
  { key: "pillar", header: "pillar" },
  { key: "writerId", header: "writerId" },
  { key: "designerId", header: "designerId" },
  { key: "editorId", header: "editorId" },
  { key: "reviewerId", header: "reviewerId" },
  { key: "publishDate", header: "publishDate" },
  { key: "driveFileId", header: "driveFileId" },
  { key: "driveFileUrl", header: "driveFileUrl" },
  { key: "version", header: "version" },
  { key: "status", header: "status", required: true },
  { key: "revisionNotes", header: "revisionNotes" },
  { key: "approvalNotes", header: "approvalNotes" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const meetingColumns: Array<SheetColumn<Meeting & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "title", header: "title", required: true },
  { key: "type", header: "type" },
  { key: "clientId", header: "clientId" },
  { key: "projectId", header: "projectId" },
  { key: "taskId", header: "taskId" },
  { key: "startAt", header: "startAt", required: true },
  { key: "endAt", header: "endAt", required: true },
  { key: "attendees", header: "attendees" },
  { key: "googleCalendarEventId", header: "googleCalendarEventId" },
  { key: "meetingUrl", header: "meetingUrl" },
  { key: "notes", header: "notes" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const financeColumns: Array<SheetColumn<FinanceRecord & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "clientId", header: "clientId", required: true },
  { key: "invoiceNumber", header: "invoiceNumber", required: true },
  { key: "amount", header: "amount", required: true },
  { key: "currency", header: "currency", required: true },
  { key: "status", header: "status", required: true },
  { key: "dueDate", header: "dueDate" },
  { key: "notes", header: "notes" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
  { key: "updatedAt", header: "updatedAt", required: true },
  { key: "updatedBy", header: "updatedBy", required: true },
];

export const paymentColumns: Array<SheetColumn<Payment & Record<string, unknown>>> = [
  { key: "id", header: "id", required: true },
  { key: "financeId", header: "financeId", required: true },
  { key: "clientId", header: "clientId", required: true },
  { key: "amount", header: "amount", required: true },
  { key: "paidAt", header: "paidAt", required: true },
  { key: "method", header: "method" },
  { key: "notes", header: "notes" },
  { key: "createdAt", header: "createdAt", required: true },
  { key: "createdBy", header: "createdBy", required: true },
];

const idOnlyColumns = [{ key: "id", header: "id", required: true }] as Array<
  SheetColumn<Record<string, unknown>>
>;

export const requiredSheets = [
  { name: sheetNames.employees, columns: employeeColumns },
  { name: sheetNames.invitations, columns: invitationColumns },
  { name: sheetNames.leads, columns: leadColumns },
  { name: sheetNames.deals, columns: dealColumns },
  { name: sheetNames.pipelineMovements, columns: pipelineMovementColumns },
  { name: sheetNames.clients, columns: clientColumns },
  { name: sheetNames.clientContacts, columns: idOnlyColumns },
  { name: sheetNames.projects, columns: projectColumns },
  { name: sheetNames.tasks, columns: taskColumns },
  { name: sheetNames.content, columns: contentColumns },
  { name: sheetNames.meetings, columns: meetingColumns },
  { name: sheetNames.finance, columns: financeColumns },
  { name: sheetNames.payments, columns: paymentColumns },
  { name: sheetNames.auditLogs, columns: auditLogColumns },
  { name: sheetNames.notifications, columns: notificationColumns },
  { name: sheetNames.activity, columns: idOnlyColumns },
  { name: sheetNames.settings, columns: idOnlyColumns },
  { name: sheetNames.rolePermissions, columns: idOnlyColumns },
];
